apiVersion: batch/v1
kind: CronJob
metadata:
  name: rpa-faturas-deployment
spec:
  schedule: cronSchedule
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: rpa-faturas
            image: joaoallmeida/rpa-faturas:latest
            envFrom:
              - secretRef:
                  name: credentials
          restartPolicy: OnFailure
        
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  BRK_USER: brkUser
  BRK_PASSWORD: brkPassword
  ENEL_USER: enelUser
  ENEL_PASSWORD: enelPassword
  ENEL_KEY: enelKey