apiVersion: batch/v1
kind: CronJob
metadata:
  name: rpa-faturas-deployment
spec:
  schedule: cronSchedule
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: rpa-faturas
            image: joaoallmeida/rpa-faturas:latest
            envFrom:
              - secretRef:
                  name: credentials
          restartPolicy: OnFailure
        
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  BRK_USER: Z2lzZWxlYWxtZWlkYTc5QG91dGxvb2suY29t
  BRK_PASSWORD: R2lzYTE5Nzk=
  ENEL_USER: am9hb2FsbG1laWRhOTZAZ21haWwuY29t
  ENEL_PASSWORD: UDRsbTNpckBz
  ENEL_KEY: QUl6YVN5QXo0SnhORjNyaWo1TjBZMmdzQVRCVjhhbVlNdEMzTXpr