apiVersion: v1
kind: Pod
metadata:
  name: jenkins-docker
  namespace: devops-tools
spec:
  containers:
  - name: docker
    image: docker:dind
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock